### PR TITLE
fixed endless loading of collab tab and redirect to /tz problem

### LINKED ISSUE #2: Collabs page displays a loading indicator forever when you don't have collabs.

### PR DESCRIPTION
**Pull request by xat**
this fixes the problem mentioned in https://github.com/teia-community/teia-ui/issues/2 and a further problem that triggered a redirect to '/tz' when clicking on the collab tab as a user without subjkt.

### CODE REVIEW

File: src/pages/display/index.js [hunk 1]
```diff
@@ -579,12 +579,11 @@ export default class Display extends Component {
...
     }
 
-    this.updateLocation('collabs')
-  }
-
-  updateLocation = (slug) => {
-    const { subjkt, wallet } = this.state
-    this.props.history.push(`/${subjkt === '' ? wallet : subjkt}/${slug}`)
+    if (this.state.subjkt !== '') {
+      this.props.history.push(`/${this.state.subjkt}/collabs`)
```
Comment (melMass) [inline src/pages/display/index.js]: Can't we just always resolve to the address?

Comment (xat) [reply src/pages/display/index.js]: hmm, it's done like this in the other tabs as well and ensures that the url contains the username.

Comment (melMass) [reply src/pages/display/index.js]: Ah my bad, I thought routing handled these

**Review by LeonNicholls — APPROVED** [review]
LGTM

**Review by LeonNicholls — APPROVED** [review]

**Comment by melMass** [comment]
@xat Very nice, do you think it's out of scope of this issue to either dim the tab title, or show `No Collaborations` in the "grid view" ?

**Review by melMass — COMMENTED** [review]
@xat Very nice, do you think it's out of scope of this issue to either dim the tab title (or hide?), or show No Collaborations in the "grid view" ?

**Comment by melMass** [comment]
@xat I made a simple proposal in 6151985157c5c1889037acfe6e7b930f55a25c2a

image

**Comment by melMass** [comment]
Also added collections, discard loading components if the objkts length === 0

image

**Comment by melMass** [comment]
This might more be out of scope for this issue,
but the first render of an artist page is strange, to reproduce, go to the feed: https://teia-ui-pr-32.onrender.com/
Click on an artist name down an objkt, there! something strange happens on "route resolution"
The name is already resolved so it should be used as the path when there is a SUBJKT

**Comment by melMass** [comment]
(rebased)

File: src/pages/display/index.js [hunk 2]
```diff
@@ -1062,151 +1065,166 @@ export default class Display extends Component {
...
+          <CollabsTab
+            wallet={this.state.wallet}
+            filter={this.state.filter}
+            onLoaded={this.disableLoading}
+          />
         )}
-
-        {!this.state.loading && this.state.collectionState && (
-          <div>
+        {((this.state.collabsState && this.state.collabs.length === 0) ||
```
Comment (xat) [inline src/pages/display/index.js]: collabs length is always 0 because they are loaded in the CollabsTab component. this means currently always 'No Collabs' is shown.

Bildschirmfoto 2022-03-23 um 08 09 11

Comment (xat) [reply src/pages/display/index.js]: fixed

**Comment by xat** [comment]
did some small refactorings on the tab logic, moved the empty-state of the collabs tab into the CollabsTab component, and added the empty-state to the creations tab as well.

this means another round of testing is needed :-)

i think this whole component needs heavy refactoring and would greatly benefit from a library like `useSWR`.

yes, the routing is somehow odd and also needs refactoring. the link to the artist subpage from the start-page should directly point to the slug-version of the artist profile if the artist has a slug, so that these redirects are not needed in the first place. but imo fixing that is out of scope for this pr.

**Comment by melMass** [comment]
> i think this whole component needs heavy refactoring and would greatly benefit from a library like `useSWR`.

Yes my first commit I realised I did not understand it was a huge "if" list 😅 .....
Thanks for the fix! Another thing I've realised is that we can also have `loaded = false` & `collection.length==0` for a second when landing on the tab. There might be a more clever way to avoid that...

**Comment by melMass** [comment]
I tested it a bit and it seems to be working well!

For the creation I think it messes up with the no-route bug, to test go to https://teia-ui-pr-32.onrender.com/ROBNESS_V3

**Review by melMass — CHANGES_REQUESTED** [review]
Looks good !

I just have the dead road issue resulting in a blank profile with "no creation":
https://teia-ui-pr-32.onrender.com/ROBNESS_V3

Should'nt we have a 404?

**Comment by xat** [comment]
yes, that's a problem since forever. see for example https://www.hicetnunc.xyz/ROBNESS_V3

do we want to tackle it as part of this pr? otherwise, i would suggest that one of the designers comes up with a nice TEIA-404 image and we implement that in a separate issue.

**Comment by xat** [comment]
> > i think this whole component needs heavy refactoring and would greatly benefit from a library like `useSWR`.
> 
> Yes my first commit I realised I did not understand it was a huge "if" list 😅 ..... Thanks for the fix! Another thing I've realised is that we can also have `loaded = false` & `collection.length==0` for a second when landing on the tab. There might be a more clever way to avoid that...

`useSWR` would be the more clever way, but a complete refactor of the component would be needed :-)

**Comment by melMass** [comment]
> i would suggest that one of the designers comes up with a nice TEIA-404 image and we implement that in a separate issue.

Yep agreed! Let's open a dedicated issue for other devs to pickup ;)

**Review by melMass — APPROVED** [review]
